package br.com.weinersilva.integracao.enums;

public enum Pais {
	AFEGANISTÃO(4,"Afeganistão"),
	ÁFRICADOSUL(710,"África do Sul"),
	ALBÂNIA(8,"Albânia"),
	ALEMANHA(276,"Alemanha"),
	ANDORRA(20,"Andorra"),
	ANGOLA(24,"Angola"),
	ANGUILLA(660,"Anguilla"),
	ANTÍGUAEBARBUDA(28,"Antígua e Barbuda"),
	ARÁBIASAUDITA(682,"Arábia Saudita"),
	ARGÉLIA(12,"Argélia"),
	ARGENTINA(32,"Argentina"),
	ARMÊNIA(51,"Armênia"),
	ARUBA(533,"Aruba"),
	AUSTRÁLIA(36,"Austrália"),
	ÁUSTRIA(40,"Áustria"),
	AZERBAIJÃO(31,"Azerbaijão"),
	BAHAMAS(44,"Bahamas"),
	BANGLADESH(50,"Bangladesh"),
	BARBADOS(52,"Barbados"),
	BAREIN(48,"Barein"),
	BÉLGICA(56,"Bélgica"),
	BELIZE(84,"Belize"),
	BENIN(204,"Benin"),
	BERMUDA(60,"Bermuda"),
	BIELORÚSSIA(112,"Bielorússia"),
	BOLÍVIA(68,"Bolívia"),
	BONAIRESANTOEUSTÁQUIOESABA(535,"Bonaire, Santo Eustáquio e Saba"),
	BÓSNIAHERZEGOVINA(70,"Bósnia-Herzegovina"),
	BOTSUANA(72,"Botsuana"),
	BRASIL(76,"Brasil"),
	BRUNEI(96,"Brunei"),
	BULGÁRIA(100,"Bulgária"),
	BURKINAFASO(854,"Burkina Faso"),
	BURUNDI(108,"Burundi"),
	BUTÃO(64,"Butão"),
	CABOVERDE(132,"Cabo Verde"),
	CAMARÕES(120,"Camarões"),
	CAMBOJA(116,"Camboja"),
	CANADÁ(124,"Canadá"),
	CASAQUISTÃO(398,"Casaquistão"),
	CATAR(634,"Catar"),
	CHADE(148,"Chade"),
	CHILE(152,"Chile"),
	CHINA(156,"China"),
	CHINAHONGKONG(344,"China, Hong Kong"),
	CHINAMACAO(446,"China, Macao"),
	CHIPRE(196,"Chipre"),
	CINGAPURA(702,"Cingapura"),
	COLÔMBIA(170,"Colômbia"),
	COMORES(174,"Comores"),
	CONGO(178,"Congo"),
	CORÉIADONORTE(408,"Coréia do Norte"),
	CORÉIADOSUL(410,"Coréia do Sul"),
	COSTADOMARFIM(384,"Costa do Marfim"),
	COSTARICA(188,"Costa Rica"),
	CROÁCIA(191,"Croácia"),
	CUBA(192,"Cuba"),
	CURAÇAO(531,"Curaçao"),
	DINAMARCA(208,"Dinamarca"),
	DJIBOUTI(262,"Djibouti"),
	DOMINICA(212,"Dominica"),
	EGITO(818,"Egito"),
	ELSALVADOR(222,"El Salvador"),
	EMIRADOSÁRABESUNIDOS(784,"Emirados Árabes Unidos"),
	EQUADOR(218,"Equador"),
	ERITRÉIA(232,"Eritréia"),
	ESLOVÁQUIA(703,"Eslováquia"),
	ESLOVÊNIA(705,"Eslovênia"),
	ESPANHA(724,"Espanha"),
	ESTADOSUNIDOSDAAMÉRICA(840,"Estados Unidos da América"),
	ESTÔNIA(233,"Estônia"),
	ETIÓPIA(231,"Etiópia"),
	FIJI(242,"Fiji"),
	FILIPINAS(608,"Filipinas"),
	FINLÂNDIA(246,"Finlândia"),
	FRANÇA(250,"França"),
	GABÃO(266,"Gabão"),
	GÂMBIA(270,"Gâmbia"),
	GANA(288,"Gana"),
	GEÓRGIA(268,"Geórgia"),
	GIBRALTAR(292,"Gibraltar"),
	GRANADA(308,"Granada"),
	GRÉCIA(300,"Grécia"),
	GROENLÂNDIA(304,"Groenlândia"),
	GUAM(316,"Guam"),
	GUATEMALA(320,"Guatemala"),
	GUERNSEY(831,"Guernsey"),
	GUIANA(328,"Guiana"),
	GUIANAFRANCESA(254,"Guiana Francesa"),
	GUINÉ(324,"Guiné"),
	GUINÉEQUATORIAL(226,"Guiné Equatorial"),
	GUINÉBISSAU(624,"Guiné-Bissau"),
	HAITI(332,"Haiti"),
	HOLANDA(528,"Holanda"),
	HONDURAS(340,"Honduras"),
	HUNGRIA(348,"Hungria"),
	IÊMEN(887,"Iêmen"),
	ILHADEMAN(833,"Ilha de Man"),
	ILHAGUADALUPE(312,"Ilha Guadalupe"),
	ILHANORFOLK(574,"Ilha Norfolk"),
	ILHAREUNIÃO(638,"Ilha Reunião"),
	ILHASALANDA(248,"Ilhas Alanda"),
	ILHASCAYMAN(136,"Ilhas Cayman"),
	ILHASCOOK(184,"Ilhas Cook"),
	ILHASDOCANAL(830,"Ilhas do Canal"),
	ILHASFAEROE(234,"Ilhas Faeroe"),
	ILHASFALKLAND(238,"Ilhas Falkland"),
	ILHASMARIANAS(580,"Ilhas Marianas"),
	ILHASMARSHALL(584,"Ilhas Marshall"),
	ILHASSALOMÃO(90,"Ilhas Salomão"),
	ILHASTURKSECAICOS(796,"Ilhas Turks e Caicos"),
	ILHASVIRGENS(850,"Ilhas Virgens"),
	ILHASVIRGENSBRITÂNICAS(92,"Ilhas Virgens Britânicas"),
	ILHASWALLISEFUTUNA(876,"Ilhas Wallis e Futuna"),
	ÍNDIA(356,"Índia"),
	INDONÉSIA(360,"Indonésia"),
	IRÃ(364,"Irã"),
	IRAQUE(368,"Iraque"),
	IRLANDA(372,"Irlanda"),
	ISLÂNDIA(352,"Islândia"),
	ISRAEL(376,"Israel"),
	ITÁLIA(380,"Itália"),
	JAMAICA(388,"Jamaica"),
	JAPÃO(392,"Japão"),
	JERSEY(832,"Jersey"),
	JORDÂNIA(400,"Jordânia"),
	KIRIBATI(296,"Kiribati"),
	KUWAIT(414,"Kuwait"),
	LAOS(418,"Laos"),
	LESOTO(426,"Lesoto"),
	LETÔNIA(428,"Letônia"),
	LÍBANO(422,"Líbano"),
	LIBÉRIA(430,"Libéria"),
	LÍBIA(434,"Líbia"),
	LIECHTENSTEIN(438,"Liechtenstein"),
	LITUÂNIA(440,"Lituânia"),
	LUXEMBURGO(442,"Luxemburgo"),
	MACEDÔNIA(807,"Macedônia"),
	MADAGÁSCAR(450,"Madagáscar"),
	MALÁSIA(458,"Malásia"),
	MALAUÍ(454,"Malauí"),
	MALDIVAS(462,"Maldivas"),
	MALI(466,"Mali"),
	MALTA(470,"Malta"),
	MARROCOS(504,"Marrocos"),
	MARTINICA(474,"Martinica"),
	MAURÍCIO(480,"Maurício"),
	MAURITÂNIA(478,"Mauritânia"),
	MAYOTTE(175,"Mayotte"),
	MÉXICO(484,"México"),
	MIANMA(104,"Mianma"),
	MICRONÉSIA(583,"Micronésia"),
	MOÇAMBIQUE(508,"Moçambique"),
	MOLDÁVIA(498,"Moldávia"),
	MÔNACO(492,"Mônaco"),
	MONGÓLIA(496,"Mongólia"),
	MONTENEGRO(499,"Montenegro"),
	MONTSERRAT(500,"Montserrat"),
	NAMÍBIA(516,"Namíbia"),
	NAURU(520,"Nauru"),
	NEPAL(524,"Nepal"),
	NICARÁGUA(558,"Nicarágua"),
	NÍGER(562,"Níger"),
	NIGÉRIA(566,"Nigéria"),
	NIUE(570,"Niue"),
	NORUEGA(578,"Noruega"),
	NOVACALEDÔNIA(540,"Nova Caledônia"),
	NOVAZELÂNDIA(554,"Nova Zelândia"),
	OMÃ(512,"Omã"),
	PALAU(585,"Palau"),
	PALESTINA(275,"Palestina"),
	PANAMÁ(591,"Panamá"),
	PAPUANOVAGUINÉ(598,"Papua Nova Guiné"),
	PAQUISTÃO(586,"Paquistão"),
	PARAGUAI(600,"Paraguai"),
	PERU(604,"Peru"),
	PITCAIRN(612,"Pitcairn"),
	POLINÉSIAFRANCESA(258,"Polinésia Francesa"),
	POLÔNIA(616,"Polônia"),
	PORTORICO(630,"Porto Rico"),
	PORTUGAL(620,"Portugal"),
	QUÊNIA(404,"Quênia"),
	QUIRGUISTÃO(417,"Quirguistão"),
	REINOUNIDO(826,"Reino Unido"),
	REPÚBLICACENTROAFRICANA(140,"República Centro Africana"),
	REPÚBLICADEMOCRÁTICADOCONGO(180,"República Democrática do Congo"),
	REPÚBLICADOMINICANA(214,"República Dominicana"),
	REPÚBLICATCHECA(203,"República Tcheca"),
	ROMÊNIA(642,"Romênia"),
	RUANDA(646,"Ruanda"),
	RÚSSIA(643,"Rússia (Federação Russa)"),
	SAARAOCIDENTAL(732,"Saara Ocidental"),
	SAINTMARTIN(663,"Saint Martin"),
	SAINTPIERREEMIQUELON(666,"Saint Pierre e Miquelon"),
	SAMOA(882,"Samoa"),
	SAMOAAMERICANA(16,"Samoa Americana"),
	SANMARINO(674,"San Marino"),
	SANTAHELENA(654,"Santa Helena"),
	SANTALÚCIA(662,"Santa Lúcia"),
	SÃOBARTOLOMEU(652,"São Bartolomeu"),
	SÃOCRISTÓVÃOENEVIS(659,"São Cristóvão e Nevis"),
	SÃOTOMEEPRÍNCIPE(678,"São Tome e Príncipe"),
	SÃOVICENTEEGRANADINAS(670,"São Vicente e Granadinas"),
	SARK(680,"Sark"),
	SEICHELLES(690,"Seichelles"),
	SENEGAL(686,"Senegal"),
	SERRALEOA(694,"Serra Leoa"),
	SÉRVIA(688,"Sérvia"),
	SÍRIA(760,"Síria"),
	SOMÁLIA(706,"Somália"),
	SRILANKA(144,"Sri Lanka"),
	SUAZILÂNDIA(748,"Suazilândia"),
	SUDÃODOSUL(728,"Sudão do Sul"),
	SUDÃO(729,"Sudão"),
	SUÉCIA(752,"Suécia"),
	SUÍÇA(756,"Suíça"),
	SURINAME(740,"Suriname"),
	SVALBARDEJANMAYENISLANDS(744,"Svalbard e Jan Mayen Islands"),
	TADJIQUISTÃO(762,"Tadjiquistão"),
	TAILÂNDIA(764,"Tailândia"),
	TANZÂNIA(834,"Tanzânia"),
	TIMORLESTE(626,"Timor Leste"),
	TOGO(768,"Togo"),
	TOKELAU(772,"Tokelau"),
	TONGA(776,"Tonga"),
	TRINIDADETOBAGO(780,"Trinidad e Tobago"),
	TUNÍSIA(788,"Tunísia"),
	TURCOMENISTÃO(795,"Turcomenistão"),
	TURQUIA(792,"Turquia"),
	TUVALU(798,"Tuvalu"),
	UCRÂNIA(804,"Ucrânia"),
	UGANDA(800,"Uganda"),
	URUGUAI(858,"Uruguai"),
	UZBEQUISTÃO(860,"Uzbequistão"),
	VANUATU(548,"Vanuatu"),
	VATICANO(336,"Vaticano"),
	VENEZUELA(862,"Venezuela"),
	VIETNÃ(704,"Vietnã"),
	ZÂMBIA(894,"Zâmbia"),
	ZIMBÁBUE(716,"Zimbábue");
	
	private int codigo;
	private String descricao;
	
	Pais(){
		
	}
	
	private Pais(int codigo, String descricao) {
		this.codigo = codigo;
		this.descricao = descricao;
	}

	public int getCodigo() {
		return codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
	
}
